### ISSUE TITLE
Marketplace modals are too tall to show notifications

### ISSUE THREAD

**Issue by theRealPadster** [Tetrax-10/Nord-Spotify#1]
I was testing the error notifications and noticed that in your theme, it makes the modals all tall. Since `Spicetify.showNotification` shows up underneath for some reason, this means you can't see them when they are triggered. 

They normally show up around here, on the layer underneath the modal. 
<img width="846" alt="image" src="https://user-images.githubusercontent.com/1565883/193147590-cfe526f7-fee8-4bc4-8e45-75274c78fefe.png">

**Comment by Tetrax-10** [comment]
That bug has been fixed in the latest Version 3.0. Thx for reporting ♥️. Feel free to report any bugs if you find any 🤗.
