### ISSUE TITLE
Classic green active items?

### ISSUE THREAD

**Issue by tails-pm** [Tetrax-10/Nord-Spotify#11]
In Spotify's default theme the hearts, currently playing, shuffle, loop and others are green. is there a way to have the classic colors and all with the Nord theme?

**Comment by Tetrax-10** [comment]
Yes, go to Nord Spotify settings and choose Spotify Theme
![image](https://user-images.githubusercontent.com/75513645/204921577-39782a24-9d6c-459e-880f-dc8fce95b711.png)

**Comment by tails-pm** [comment]
The thing is it doesn't seem to work?

**Comment by Tetrax-10** [comment]
> The thing is it doesn't seem to work?

wdym? send a clear ss to explain

**Comment by tails-pm** [comment]
![image](https://user-images.githubusercontent.com/36506357/205241375-aacb61dd-4fdb-46b6-9b7a-4a99d7012d3e.png)
all of the hearts and the shuffle buttons are white by default, it seems the color pallet doesn't allow me to change them independently

**Comment by Tetrax-10** [comment]
> all of the hearts and the shuffle buttons are white by default, it seems the color pallet doesn't allow me to change them independently

its Nord Spotify's behaviour you can change them by writting your own css snippet or edit the theme locally (need css knowledge)

**Comment by tails-pm** [comment]
I see, thank you!
