### ISSUE TITLE
Cover Image bleeding into playlist, when enhanced

### ISSUE THREAD

**Issue by noxan-dev** [Tetrax-10/Nord-Spotify#12]
As the title states, the cover image is bleeding into the Liked Songs and only the liked songs. It seems only to happen when Enhanced is active. 

Also, not sure if this is supposed to be the functionality, the banner for liked songs changes to the current song image regardless if you are playing a song from liked songs or if the song is not liked and in that playlist.

Spotify: 1.2.0
Spictify: 2.15.0

![image](https://user-images.githubusercontent.com/59417659/209358074-45299758-2a21-441b-8da1-e48bb03a1a5b.png)

![image](https://user-images.githubusercontent.com/59417659/209358116-ae266719-320a-4da6-bbe7-f4b7aaf5c70e.png)

**Comment by Tetrax-10** [comment]
Its working fine for me in liked songs page aswell as enhanced songs in a playlist
![image](https://user-images.githubusercontent.com/75513645/209376861-67178a94-9719-40f4-9bba-e1dec283fb8b.png)
![image](https://user-images.githubusercontent.com/75513645/209376968-077b9f82-ba3e-4fde-a045-6bba68e4a1b6.png)
can u share ur config? ( run `spicetify config` and send the SS)

**Comment by noxan-dev** [comment]
![image](https://user-images.githubusercontent.com/59417659/209392112-e55a9e2e-7798-4f43-80c0-2e93cd702e58.png)

**Comment by Tetrax-10** [comment]
try using this latest [version](https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.1.968.g21027577-2.exe) of spotify and after installing run `spicetify backup apply`. it should prob fix it

**Comment by noxan-dev** [comment]
That didn't fix it. I uninstalled spicetify and Spotify, but it's still happening. 

Initially, I downloaded the theme from the marketplace, but after seeing others with the same issue and your recommendation to get the one using PowerShell, I uninstalled the marketplace one and installed the other. 

Is there a place I can check for residual files that might still be around from the marketplace version?

**Comment by Tetrax-10** [comment]
> Is there a place I can check for residual files that might still be around from the marketplace version?

No

Can you check is there any errors from nord in spotify devtools?

**Comment by Tetrax-10** [comment]
> ![image](https://user-images.githubusercontent.com/59417659/209358074-45299758-2a21-441b-8da1-e48bb03a1a5b.png)
> ![image](https://user-images.githubusercontent.com/59417659/209358116-ae266719-320a-4da6-bbe7-f4b7aaf5c70e.png)

Also what page is this liked songs? playlist?

**Comment by noxan-dev** [comment]
yea it is liked

**Comment by Tetrax-10** [comment]
I dont have a enhance button in liked songs page, but i have that that button in playlist page.
can you check once again you have a enhance button in liked songs page?
because enahced songs in other pages causes this issue and i fixed it, i dont know liked songs page has a enhance button
![image](https://user-images.githubusercontent.com/75513645/209405082-7e234ee0-463f-47df-94a5-18a3df39a5f5.png)

**Comment by noxan-dev** [comment]
![image](https://user-images.githubusercontent.com/59417659/209406123-5a19ef85-d284-4d03-99a1-9d10007dac35.png)

**Comment by noxan-dev** [comment]
It's in the experimental features 

![image](https://user-images.githubusercontent.com/59417659/209406343-41e239a1-6162-4739-aaf8-e52f5aea8f36.png)

**Comment by Tetrax-10** [comment]
> It's in the experimental features

Fixed It 🎉, Never knew this setting existed
If your issue is fixed feel free to close this issue 👇
Thanks for reporting and and being patient till I understood the problem ❤️

**Comment by noxan-dev** [comment]
Thx, it's fixed! No worries, I've been using the setting for a while. I forgot I needed to enable it.
