### ISSUE TITLE
Sidebar color bug when click on "Your Library" tab and home button icon disappeared when not hover.

### ISSUE THREAD

**Issue by vathanac** [Tetrax-10/Nord-Spotify#14]
![image](https://user-images.githubusercontent.com/87689818/210214711-374435e4-4846-4514-94e2-652bc7066fe9.png)

Spotify for Windows
1.2.1.968.g21027577

Install via powershell script(Auto update)

**Comment by vathanac** [comment]
Uncheck "Highlight SideBar Selected Items ( Main Items )" 
Still have the same issue

![image](https://user-images.githubusercontent.com/87689818/210216117-61a08c63-362f-427d-aa62-20db073fc4af.png)

**Comment by vathanac** [comment]
roll back to 1.2.O.1165.gabf054ab fix the issue

**Comment by Tetrax-10** [comment]
Am currently on vacation so cant fix that now, but sure i will fix that in this week. thx for ur patience 🤗

**Comment by Tetrax-10** [comment]
Fixed it on the latest release. you can upgrade your spotify and spicetify to the latest version.
Thx for reporting the bug 🥰
