### ISSUE TITLE
Dynamic color resets after opening different playlist

### ISSUE THREAD

**Issue by tomini** [Tetrax-10/Nord-Spotify#15]
Hello,
when I use the _Dynamic theme_ with _Atmosphere (Best)_ mode and click into another playlist it resets to a grey color.
![image](https://user-images.githubusercontent.com/41676221/211432351-504ac9e0-a262-4c4c-9335-364f1ec68a32.png)
Playing song: 
![image](https://user-images.githubusercontent.com/41676221/211432400-4dc69166-6d66-48a9-bbff-1a7816e5a579.png)
After clicking to another playlist: 
![image](https://user-images.githubusercontent.com/41676221/211432424-35fa69f0-ac8b-405e-bc93-58d8104b1d85.png)
If I go back into the playing playlist and doubleclick on the playing song/start it over the color stays gray. I have to start another song so the dynamic theme reacts.
If I use any other mode like _Average of Colors_ or _Dark/Light Vibrant_, this behaviour doesn't occur.

Is this normal for the Atmosphere mode?
Thanks

> PS: My config:
> ![image](https://user-images.githubusercontent.com/41676221/211433045-47c83ae4-7eb4-4620-9dca-251838939968.png)
> I tried installing it via Marketplace and the Powershell script.

**Comment by Tetrax-10** [comment]
Nord Spotify Changes color when the cover art changes. Song change, page change such as switching to a diff playlist page can cause the cover art to change. If the cover art chagnes dynamic color changes.

This bug occurs in `Made for You` playlists, as the cover art for `made for you` playlist's are in diff format, `Atmosphere` mode is not supported its not fixable as thats how spotify intended to format those cover arts. So all modes except `Atmosphere` can work with `Made for You` playlists


https://user-images.githubusercontent.com/75513645/211516886-4db9da7d-ccac-4985-8ee7-64a5fa1350bd.mp4

**Comment by Tetrax-10** [comment]
[JulienMaille's](https://github.com/JulienMaille) [dribbblish-dynamic-theme](https://github.com/JulienMaille/dribbblish-dynamic-theme) and [spicetify-dynamic-theme](https://github.com/JulienMaille/spicetify-dynamic-theme) dont have those bugs as they just use spotify's default color extraction method. but Nord Spotify's Atmosphere mode gets accurate colors from a API request where only user, playlist, song cover art are supported (no support for made for you, radio).

Use this option to disable cover art while page change
![image](https://user-images.githubusercontent.com/75513645/211714263-b9e0f224-36d9-446f-9569-b9f94d2b9ca9.png)
