### ISSUE TITLE
Missing "similar playlists" at bottom of playlist page

### ISSUE THREAD

**Issue by terminalPoltergeist** [Tetrax-10/Nord-Spotify#16]
Is there a way to get the list of similar playlists that shows at the bottom on a playlist?

**Comment by Tetrax-10** [comment]
I have never heared of `similar playlists` under spotify playlist page. there will be only similar songs under a playlists.
You can describe your problem with a screenshot so i cant understand easly

**Comment by terminalPoltergeist** [comment]
Apologies, I was mistakenly referring to the discography section at the bottom of an album.. lack of sleep can make you see funny things..
