### ISSUE TITLE
Atmosphere Dynamic Color Mode not working

### ISSUE THREAD

**Issue by arifesat** [Tetrax-10/Nord-Spotify#17]
Atmosphere mode doesn't work, the app stays with the color of the previous theme's color. The other 3 dynamic modes work fine.

**Comment by Tetrax-10** [comment]
send me your config. Also make sure your internet cconnection is on.

**Comment by arifesat** [comment]
`[Setting]
spotify_path            = /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
inject_css              = 1
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0
prefs_path              = /home/arif/.var/app/com.spotify.Client/config/spotify/prefs
current_theme           = Nord-Spotify
color_scheme            = Spotify
overwrite_assets        = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions            = injectNord.js
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.84.716.gc5f8b819
with    = 2.16.0`

I also tried installing from marketplace but doesn't work.

**Comment by Tetrax-10** [comment]
Can you enable dev tools in spotify and run this code and send me the output screenshot
```js
(await Spicetify.CosmosAsync.get(
                `https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchExtractedColors&variables={"uris":["spotify:image:ab67616d0000b2736ac1ad714f815e19c2372401"]}&extensions={"persistedQuery":{"version":1,"sha256Hash":"d7696dd106f3c84a1f3ca37225a1de292e66a2d5aced37a66632585eeb3bbbfa"}}`
            )).data.extractedColors[0].colorRaw.hex
```

**Comment by arifesat** [comment]
![image](https://user-images.githubusercontent.com/43481435/212458955-75ec3701-219d-46f1-ac48-9ace92510cff.png)

**Comment by Tetrax-10** [comment]
You are in mac or linux?

**Comment by arifesat** [comment]
Linux.

**Comment by ohitstom** [comment]
> Linux.

update your Spotify to 2.0.

**Comment by arifesat** [comment]
> update your Spotify to 2.0.

**Comment by arifesat** [comment]
> update your Spotify to 2.0.
Ohh, now I see the problem. I was using 8 months old Flatpak package which is still not updated. I am on Fedora and lpf-spotify doesn't seem to work, also I don't want to use snaps. I have to wait for a new update for the Flatpak package then. 

Thanks for clarifying.

**Comment by svemat01** [comment]
Running version `Spotify version 1.1.99.878.g1e4ccc6e` produces the same console output. I'm using the `spotify-edge` AUR package so should be up to date. As far as I've seen there is no Spotify 2.0 client version. If there is, feel free to correct me.

**Comment by svemat01** [comment]
The following console output is also sent on each song change.
![image](https://user-images.githubusercontent.com/15212818/213929587-5066e08a-f710-473f-b8f3-5904ea59a2dd.png)

**Comment by Tetrax-10** [comment]
am still working on that.
you can expect a release soon.
this problem only happens in Linux and Mac

**Comment by zero-mindset** [comment]
Just wanted to add that this mode doesn’t work for me either (MacOS)

**Comment by Tetrax-10** [comment]
Yeah this mode is not supported on mac and linux. But am still working on it to resolve. thx for reporting

**Comment by Tetrax-10** [comment]
@arifesat @svemat01 @zero-mindset

### Fixed the Bug. Can you guys confirm whether atmosphere mode is working or not?

Code changed : Tetrax-10/Nord-Spotify@86f1edca97ace9007091cacb473c409bf1f30cfd

**Comment by svemat01** [comment]
Thanks, I tried reinstalling nord spotify using spicetify marketplace but atmosphere mode still seems broken sadly. Any command I could run to verify this in my instance or is further action needed from my side to get it working?

**Comment by zero-mindset** [comment]
It’s fixed for me on MacOS!

**Comment by Tetrax-10** [comment]
> Thanks, I tried reinstalling nord spotify using spicetify marketplace but atmosphere mode still seems broken sadly. Any command I could run to verify this in my instance or is further action needed from my side to get it working?

Run this code in console and screenshot me the output
```js
(await Spicetify.CosmosAsync.get(
                encodeURI(`https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchExtractedColors&variables={"uris":["spotify:image:ab67616d0000b2736ac1ad714f815e19c2372401"]}&extensions={"persistedQuery":{"version":1,"sha256Hash":"d7696dd106f3c84a1f3ca37225a1de292e66a2d5aced37a66632585eeb3bbbfa"}}`
            ))).data.extractedColors[0].colorRaw.hex
```

**Comment by svemat01** [comment]
Sorry, it turned out I needed to run `spicetify restart`. I assumed the reload prompted by the marketplace was sufficient.
Thanks for the fix, I appreciate it :)

**Comment by arifesat** [comment]
It worked for me too. Thanks for your work!
