### ISSUE TITLE
[Suggestion] Use song cover as lyric plus background.

### ISSUE THREAD

**Issue by vathanac** [Tetrax-10/Nord-Spotify#19]
Would be cool if it shows song cover instead of solid color background.

![image](https://user-images.githubusercontent.com/87689818/213444572-0f977e17-1981-4768-8823-20e36171214b.png)

**Comment by Tetrax-10** [comment]
I will think about that.
Thx for the Suggestion its a good one 🥰

**Comment by Tetrax-10** [comment]
# Done 👍

## Lyrics Plus
![Screenshot_20230130_082239](https://user-images.githubusercontent.com/75513645/215514056-822ce473-de54-42e0-a631-e2f42ec63f3b.png)

## Spotify Lyrics
![Screenshot_20230130_082418](https://user-images.githubusercontent.com/75513645/215514040-c2bb6d27-f030-4ac6-8e63-e8f10f9b91ea.png)

## Center Lyrics (bonus)
![Screenshot_20230130_082628](https://user-images.githubusercontent.com/75513645/215514060-367758f6-6fcc-417f-8faa-e487b14f04f9.png)

**Comment by Tetrax-10** [comment]
@vathanac If you face any issues please open a Isuue in this github page

**Comment by vathanac** [comment]
> @vathanac If you face any issues please open a Isuue in this github page

Thanks for the update
