### ISSUE TITLE
how to install nightly version of theme

### ISSUE THREAD

**Issue by staticanimal** [Tetrax-10/Nord-Spotify#2]
i swear i've looked everywhere but i can not for the life of me figure out how to use the darker version of this theme. in fact i can't even find the folder spicetify's decided to install itself to.

edit: disregard last. as usual i post about an issue i'm having and then instantly find the solution for it. still recommend adding better instructions for changing between regular nord and nightly though.

**Comment by Tetrax-10** [comment]
## To Change Theme's Color Scheme run these commands in Powershell/Terminal

### Nord

```
spicetify config color_scheme Nord
spicetify apply
```

### Nightly

```
spicetify config color_scheme Nightly
spicetify apply
```

Thx. I think this will help newbies to install and change color schemes easly

If you have any issues you can ask in spicetify server in discord.
