### ISSUE TITLE
font

### ISSUE THREAD

**Issue by senolfndk** [Tetrax-10/Nord-Spotify#20]
how to change font

**Comment by Tetrax-10** [comment]
## Didn't you read this?
![image](https://user-images.githubusercontent.com/75513645/216292768-d28fb87a-5f53-4e99-9c55-a8d8ad7b6160.png)

Readme Has the [Tutorial](https://github.com/Tetrax-10/Nord-Spotify#custom-fonts) to install font.

Just go throw it. And this is a issues page not a comment box

**Comment by senolfndk** [comment]
I read it, but I don't understand visually, could you please take a video and post it?
