### ISSUE TITLE
Enhancement - Turn off full banner height

### ISSUE THREAD

**Issue by noxan-dev** [Tetrax-10/Nord-Spotify#21]
Is it possible to get a setting that turns off the full banner for artist pages/playlists? Probably not a popular opinion, but personally, I don't like it taking up the entire height. Love the theme either way.

**Comment by Tetrax-10** [comment]
Working on it 👍.

**Comment by noxan-dev** [comment]
😊thx!

**Comment by shray-narang** [comment]
came here to say the same thing

**Comment by walbjorn** [comment]
Would be very much appreciated by me too. I *love* this theme apart from this aspect of fit. cheers for your work @Tetrax-10

**Comment by Tetrax-10** [comment]
# Done 🐱 !!!

https://user-images.githubusercontent.com/75513645/224494756-dd55ae40-7367-4ef0-ab0e-3a878daf3dc2.mp4

</br>

## Now you can totally disable banners if you want

![image](https://user-images.githubusercontent.com/75513645/224494781-57233338-0a09-4dab-a094-8261c74fddd0.png)
![image](https://user-images.githubusercontent.com/75513645/224494808-c7e97d0b-e6f8-4ca7-9f59-7ca238444d28.png)
