### ISSUE TITLE
Marketplace version doesn't fully apply the theme

### ISSUE THREAD

**Issue by ImCheesecake** [Tetrax-10/Nord-Spotify#22]
With the latest spotify update 1.2.4.912.g949d5fd0 and Spicetify v2.16.1, the marketplace version of the Theme doesn't fully applies. Also some UI breaks, but I guess that's something on Spicetify itself

![image](https://user-images.githubusercontent.com/43030367/217513064-f5a42541-2126-496a-a5a1-fd2ba42f0ed1.png)

**Comment by Tetrax-10** [comment]
Spotify fu**ked their new UI. So i cant do much about it. But if marketplace is not appling the theme properly then try running these commands in terminal.

```sh
spicetify config current_theme marketplace color_scheme Marketplace inject_css 1 replace_colors 1 overwrite_assets 1
```

```sh
spicetify apply
```
