### ISSUE TITLE
Enchancement - Option to disable transparent background liked songs

### ISSUE THREAD

**Issue by QazCetelic** [Tetrax-10/Nord-Spotify#24]
![image](https://user-images.githubusercontent.com/51381523/221504886-a913ae0c-ac2e-433d-956e-120e8d272dfd.png)

I personally think it makes the text hard to read with some images, could you add an option to disable the transparent background?

**Comment by Tetrax-10** [comment]
Send your config. It was a issue before but not in the latest versions.

Works good in 

Spotify for Windows
1.2.6.863.ge7902f05
Spicetify v2.16.2

**Comment by QazCetelic** [comment]
Spotify version: 1.1.84.716.gc5f8b819
Spicetify version: 2.16.2
Config:
```
[Setting]
prefs_path              = /home/qaz/.var/app/com.spotify.Client/config/spotify/prefs
color_scheme            = 
overwrite_assets        = 0
spotify_launch_flags    = 
check_spicetify_upgrade = 0
spotify_path            = /home/qaz/.local/share/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
current_theme           = marketplace
inject_css              = 1
replace_colors          = 1

[Preprocesses]
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = 
custom_apps           = marketplace
sidebar_config        = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.84.716.gc5f8b819
with    = 2.16.2
```

**Comment by Tetrax-10** [comment]
1.1.84 💀you are 30 versions behind. Nord spotify woks good on 1.1.95 >. sry i cant add support for very old spotify versions. I think there is a update for flatpack spotify. You can ask help on how to update spotify on linux in discord server

**Comment by QazCetelic** [comment]
I installed it yesterday, I didn't expect to be 30 versions behind. I'm not sure how I'm should install it because snap isn't supported by spicify and Spotify only has an official Snap and Deb build.

I'll try this again when I get it working manually.

**Comment by Tetrax-10** [comment]
Ask help in discord some linux users have 1.2.something.
