### ISSUE TITLE
Lyrics+ Tab doesn't align with the controls player properly

### ISSUE THREAD

**Issue by wadeosg** [Tetrax-10/Nord-Spotify#25]
The Lyricsplus page has some issues blending with the bottom now-playing controls ribbon.

Screenshot attatched below:

![image](https://user-images.githubusercontent.com/126545818/222144447-a8f582e6-b427-4713-9d4c-c8ec21636697.png)

Footnote:
It doesnt occur when the lyrics are loading, only when the text is on-screen.

**Comment by Tetrax-10** [comment]
will look into it
thx for reporting it

**Comment by Tetrax-10** [comment]
Fixed it. Thank you for reporting and being so patient.
