### ISSUE TITLE
Doesn't reach to bottom of the screen when maximized

### ISSUE THREAD

**Issue by vathanac** [Tetrax-10/Nord-Spotify#28]
![image](https://user-images.githubusercontent.com/87689818/226636067-b33d9779-6055-447b-9ac7-0c70cd744a87.png)

As you can see, I open a white image in background and having Spotify maximized on top of the image and there is a white line at the bottom of the screen.

**Comment by Tetrax-10** [comment]
Its a spotify bug that happens only in windows. Its not the theme's fault. Even without the spicetify that happens.
