### ISSUE TITLE
request remove the Upgrade to premium button

### ISSUE THREAD

**Issue by JackPlaysGames0510** [Tetrax-10/Nord-Spotify#30]

**Comment by Tetrax-10** [comment]
Can you send me your config and send screenshot of the upgrade button

**Comment by JackPlaysGames0510** [comment]
<img width="114" alt="Screenshot 2023-03-22 115129" src="https://user-images.githubusercontent.com/48178959/226896440-4294fd5a-6221-4e0d-9954-6cc2be6556d1.png">
I'm talking about removing this

**Comment by JackPlaysGames0510** [comment]
its in the drop-down when you click on your user name

**Comment by Tetrax-10** [comment]
Fixed in e501b1674a56751dfa8d129372c0ae7057e0d416
