### ISSUE TITLE
can you help me

### ISSUE THREAD

**Issue by JackPlaysGames0510** [Tetrax-10/Nord-Spotify#32]
i think the "Nord Spotify"s Dynamic Color Mode" doesn't work or i might be doing something wrong its like it not changing when i change it

**Comment by Tetrax-10** [comment]
@Tetrax-10 in discord
![image](https://user-images.githubusercontent.com/75513645/227698688-ee8ee9e0-4dc9-4758-99f2-7a3ebf5edad9.png)
