### ISSUE TITLE
a couple of fixes

### ISSUE THREAD

**Issue by JackPlaysGames0510** [Tetrax-10/Nord-Spotify#34]
so I turned on the library x feature on and there is a couple of little things that need to be fixed the profile image would be better if it was a circle and the song timer needs to be a bit higher because it's over the album artwork
<img width="31" alt="Screenshot 2023-04-02 003420" src="https://user-images.githubusercontent.com/48178959/229322782-cd9de7ed-57f6-440c-a630-801549d684ac.png">
<img width="241" alt="Screenshot 2023-04-02 003358" src="https://user-images.githubusercontent.com/48178959/229322783-26b11850-defc-44df-9e1b-990a6893fa49.png">

**Comment by JackPlaysGames0510** [comment]
or make the profile image not change

**Comment by Tetrax-10** [comment]
library x is a experimental feature. So I wont add support for it.

If you wanna discuss pls dont create issue. Contact me in discord

<a href="https://discord.gg/VnevqPp2Rr"><img src="https://img.shields.io/discord/842219447716151306?label=chat&logo=discord&logoColor=discord"></a>
