### ISSUE TITLE
Font doesn't apply when changing in the settings

### ISSUE THREAD

**Issue by Nthingxhere** [Tetrax-10/Nord-Spotify#36]
<img width="335" alt="Screenshot 2023-04-14 234435" src="https://user-images.githubusercontent.com/76117403/232160491-80fd2e99-1652-4cfd-aedf-f03c209e3216.png">
<img width="424" alt="Screenshot 2023-04-14 234606" src="https://user-images.githubusercontent.com/76117403/232160494-cd1b57a6-6f18-48cb-abd8-2844b811c3b7.png">

it doesn't matter which method I use to change the font either remote or local the font I choose doesn't get applied anymore.

I attached a picture to show what font is supposed to be in place and one where it doesn't function

**Comment by Tetrax-10** [comment]
Am busy with my exams so I will look into it later.

Till then try clicking that reset button in `Custom font` popup you should see `Quicksand` applied. If it get applied successfully then nothing wrong on my side. Make sure your font name and url are pasted correctly

**Comment by Nthingxhere** [comment]
> Am busy with my exams so I will look into it later.
> 
> Till then try clicking that reset button in `Custom font` popup you should see `Quicksand` applied. If it get applied successfully then nothing wrong on my side. Make sure your font name and url are pasted correctly

Will try that later and good luck with the exams!

**Comment by Nthingxhere** [comment]
I just tried resetting the font and I have bad news

the font didn't change unfortunately

**Comment by Nthingxhere** [comment]
seems to be fixed now
