### ISSUE TITLE
The metadata of the top search result is not displayed

### ISSUE THREAD

**Issue by Nortu98** [Tetrax-10/Nord-Spotify#43]
There is a problem in the search, the first search result does not display the name of the music, the artist and the type of result
![Screenshot_20230504_130121](https://user-images.githubusercontent.com/28984841/236188019-f62306d8-c862-44c1-8b49-da5c01d3f191.png)

**Comment by Tetrax-10** [comment]
Lol, I have no idea how I referenced the wrong class name. Anyway, thank you for letting me know about the issue.

![image](https://user-images.githubusercontent.com/75513645/236432593-e455f9a2-1d8f-406f-aaaa-9df338caeb3b.png)
