### ISSUE TITLE
spoitfy randomly shows tutorials nord theme library x mode 

### ISSUE THREAD

**Issue by WEKINBAD** [Tetrax-10/Nord-Spotify#44]
![Screenshot_94](https://user-images.githubusercontent.com/85103150/236779692-118e0048-f168-4c76-896a-cacb7fe3b4f9.png)

**Comment by Tetrax-10** [comment]
If you don't have any playlist then libx will tell you to create one

**Comment by Tetrax-10** [comment]
Styled it
