### ISSUE TITLE
Nord stopped working

### ISSUE THREAD

**Issue by marizzz95** [Tetrax-10/Nord-Spotify#49]
After upgrading to the latest version, Nord doesn't work anymore. Spotify stays black and there is no button to configure Nord either. I tried manual reinstall and from the marketplace but nothing works

**Comment by Tetrax-10** [comment]
Make sure your player isn't empty. Like try to play a song it should work. If still it doesn't work then send me your config and screenshot of Spotify with Nord installed.

**Comment by Tetrax-10** [comment]
Currently closing this issue as I cant replicate it. If you still facing this issue Ping `@Tetrax-10` on Discord

<p align="left"><a href="https://discord.gg/DaUbPmbDwr"><img src="https://raw.githubusercontent.com/Tetrax-10/Nord-Spotify/master/assets/join-discord-button.png" width="150px"></a></p>
