### ISSUE TITLE
gear button for settings missing

### ISSUE THREAD

**Issue by GitEin11** [Tetrax-10/Nord-Spotify#54]
the gear button for settings  beside tv mode display button is missing

I've installed nord via script, nothing, I uninstall then reinstall using market place still nothing

I'm using Ubuntu 22.04, spotify deb version 1.2.8.923.g4f94bf0d

**Comment by Tetrax-10** [comment]
Please don't use issue page as support page.

Wanna discuss or having issues with my extensions? Ping `@Tetrax-10` on Discord

<p align="left"><a href="https://discord.gg/DaUbPmbDwr"><img src="https://raw.githubusercontent.com/Tetrax-10/Nord-Spotify/master/assets/join-discord-button.png" width="150px"></a></p>

**Comment by GitEin11** [comment]
I resolve it, I just got finish reformatting my PC, so one of the first app that i install from fresh OS is spotify and ultimately your theme, then I can't configure it because gear icon is missing, the thing is I just have to play a music once and it will appear :D,  I got the problem because I was excited to use your extension without even playing any music at first, hahaha

**Comment by Tetrax-10** [comment]
haha, Nord waits for a song so it can inject banners and dynamic colors
