### ISSUE TITLE
Support for Beautiful Lyrics

### ISSUE THREAD

**Issue by boobthecat** [Tetrax-10/Nord-Spotify#55]
Currently it does not blend with the background colors. It goes on a single color instead of being dynamic.

![image](https://github.com/Tetrax-10/Nord-Spotify/assets/127695532/1d6bf953-3769-4920-a1bd-7590fa5eda1b) How it looks

![image](https://github.com/Tetrax-10/Nord-Spotify/assets/127695532/86871167-2ef4-4f50-b08f-eb10c6820a25) How it's supposed to look

**Comment by Tetrax-10** [comment]
I will add it soon, no worries 🤗.

**Comment by boobthecat** [comment]
Appreciate it!

**Comment by boobthecat** [comment]
![image](https://github.com/Tetrax-10/Nord-Spotify/assets/127695532/7a1a3409-4121-484a-b198-ef3be489f92d)
Added!

**Comment by Tetrax-10** [comment]
Oop forgot to ping the commit

https://github.com/Tetrax-10/Nord-Spotify/commit/c0beb333686dd74960b9fe42285c849f3d64700d
