### ISSUE TITLE
How to get cool song cover/lyrics on right hand side?

### ISSUE THREAD

**Issue by drakari7** [Tetrax-10/Nord-Spotify#56]
I see it on some of the screenshots but idk if this is provided by nord or spotify itself? and if yes how do I enable this banner? I'm talking about the right most side song cover and lyrics.

<img width="830" alt="image" src="https://github.com/Tetrax-10/Nord-Spotify/assets/54357427/216d74c9-8526-45cb-a8ce-084dc02ca548">

**Comment by dorianshub** [comment]
im having the same issue

**Comment by boobthecat** [comment]
![image](https://github.com/Tetrax-10/Nord-Spotify/assets/127695532/452568a9-9566-4cf9-9b62-763ab6c03fca)
