### ISSUE TITLE
How to fix the playlist cover bug

### ISSUE THREAD

**Issue by Envixittyy** [Tetrax-10/Nord-Spotify#6]
![image](https://user-images.githubusercontent.com/98817364/201506804-73ac2d6b-d7a6-44f0-8777-29850d0e23e4.png)
This happened a couple of updates ago. Would appreciate any help thanks!

**Comment by Tetrax-10** [comment]
its because you have installed dribblish theme along with nord spotify. remove dribblish theme. if you have any issues ask it in [discord](https://discord.gg/VnevqPp2Rr) not github
