### ISSUE TITLE
Can't enable the "Nightly" Nord skin

### ISSUE THREAD

**Issue by bzezzl** [Tetrax-10/Nord-Spotify#7]
I've tried everything to get the darker version of this skin, but no matter what I do, I just can't seem to make it work; I saw that someone opened an issue here and I tried the solution multiple times- I even manually installed the skin, but I can only get the original lighter blue/grey version to show. (ss below of the PowerShell command not working). I was wondering if maybe there's something I missed?

![image](https://user-images.githubusercontent.com/118148715/201567762-b9063b3c-f833-4374-9ef9-2fbcad732db6.png)

**Comment by bzezzl** [comment]
Writing this now, I just spotted that an error occurs under the spicetify line, still not sure why it occurs there though.

**Comment by Tetrax-10** [comment]
#2 
Now you can change them from nord-spotify settings. The code base have changed so this is the new method
![image](https://user-images.githubusercontent.com/75513645/201678876-6cd4df3f-25e7-4a27-bac6-120641c73245.png)

**Comment by bzezzl** [comment]
> #2 is old method Now you can change them from nord-spotify settings. The code base have changed so this is the new method ![image](https://user-images.githubusercontent.com/75513645/201678876-6cd4df3f-25e7-4a27-bac6-120641c73245.png)
> 
> if you are getting errors then once again install the theme with the installation script

Thank you for the help, the installation script + the settings method worked

**Comment by DimitrisMilonopoulos** [comment]
Is the old method still supported?
